# Generated by Django 2.2 on 2020-04-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_type', models.CharField(default='inward', max_length=10)),
                ('sub_type', models.CharField(max_length=10)),
                ('billno', models.IntegerField()),
                ('generator_gstin', models.CharField(max_length=14)),
                ('from_name', models.CharField(max_length=200)),
                ('from_address', models.CharField(max_length=200)),
                ('from_pin', models.IntegerField()),
                ('recipent_gstin', models.CharField(max_length=14)),
                ('to_name', models.CharField(max_length=200)),
                ('to_address', models.CharField(max_length=200)),
                ('to_pin', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('hsn', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=50)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tax_amt', models.DecimalField(decimal_places=2, max_digits=50)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=50)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=50)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=50)),
                ('transportNo', models.CharField(max_length=20)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('validFrom', models.DateField()),
                ('validTo', models.DateField()),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
