# Generated by Django 2.2 on 2020-04-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billno',
            field=models.IntegerField(null=True),
        ),
    ]
