# Generated by Django 2.2 on 2020-04-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebill', '0002_auto_20200403_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='hsn',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='product_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tax_rate',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
