# Generated by Django 2.2 on 2020-04-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='hsn',
            new_name='sac',
        ),
    ]
