# Generated by Django 2.2 on 2020-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayerprofile',
            name='iinput_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxpayerprofile',
            name='output_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
