# Generated by Django 2.2 on 2020-04-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200411_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxpayerprofile',
            old_name='iinput_tax',
            new_name='input_tax',
        ),
    ]
