# Generated by Django 2.2 on 2020-04-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.CharField(max_length=12, unique=True)),
                ('gst', models.DecimalField(decimal_places=0, max_digits=4)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
