# Generated by Django 2.2 on 2020-04-19 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20200418_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('gstin', models.CharField(max_length=200, null=True, unique=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('output', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('filed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Return2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('gstin', models.CharField(max_length=200, null=True, unique=True)),
                ('due_date', models.DateField()),
                ('input_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('filed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNo', models.IntegerField(null=True)),
                ('file', models.FileField(max_length=5000, upload_to='')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('due_date', models.DateField(default='2020-05-10')),
                ('gst_rate', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('recipent', models.CharField(max_length=200, null=True, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.OfficialProfile')),
                ('return1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.Return1')),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TaxpayerProfile')),
            ],
        ),
    ]
