# Generated by Django 2.2 on 2020-04-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return2',
            name='due_date',
            field=models.DateField(default='2020-05-10'),
        ),
    ]
