# Generated by Django 2.2 on 2020-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200419_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return1',
            name='gstin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='return1',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='return2',
            name='gstin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='return2',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
