# Generated by Django 2.2 on 2020-04-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20200419_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='recipent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
